[package]
name = "c-cli"
version = "0.2.0"
authors = ["Petter K <ermines-bookie-0l@icloud.com>"]
description = "cat and ls combined into one command"
edition = "2018"
license = "Apache-2.0"

[dependencies]


[[bin]]
name = "c"
path = "src/main.rs"
