[package]
name = "c-cli"
version = "0.1.0"
authors = ["Petter K <ptrkrlsrd@users.noreply.github.com>"]
description = "cat and ls combined into one command"
edition = "2018"
license = "Apache-2.0"

[dependencies]


[[bin]]
name = "c"
path = "src/main.rs"
